language: python
python: "3.6"
cache: pip
before_install:
  - pip install -U pip
  - pip install pipenv
script:
  - cp Pipfile.good Pipfile
  - cp Pipfile.good.lock Pipfile.lock
  - pipenv sync
  - pipenv run python test.py # should succeed

  - cp Pipfile.bad Pipfile
  - cp Pipfile.bad.lock Pipfile.lock
  - pipenv sync
  - pipenv run python test.py # should fail
